$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  toolchain: 'bun'

tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - '/tsconfig.base.json'
